### ISSUE TITLE
Ricgraph

### ISSUE THREAD

**Issue by RikDTJanssen** [UtrechtUniversity/awesome-utrecht-university#12]
**What is your project about?**
With Ricgraph (https://github.com/UtrechtUniversity/ricgraph), you can create a graph from research information that is stored in various source systems. You can explore this graph and discover relations you were not aware of. We have developed Ricgraph (Research in context graph) because our university had a need to be able to show our researchers, their skills, suborganizations (e.g. faculties, departments), projects and research outputs (e.g. publications, datasets, software packages) in relation to each other. This information is stored in different systems, such as Pure, OpenAlex, Yoda, the Research Software Directory, and our organization’s employee pages.

**Why do you think your project is a great addition?**
What if… we look at research information as a graph? We would have relations between objects, we would be able to “walk” from one object to another, and related objects would be neighbors. For example, starting with a researcher, this person’s publications are only one step away by following one edge, and other contributors to that publication are again one step (edge) away.

With Ricgraph, you can create a graph from research information that is stored in various source systems. You can explore this graph and discover relations you were not aware of. We have developed Ricgraph (Research in context graph) because our university had a need to be able to show our researchers, their skills, suborganizations (e.g. faculties, departments), projects and research outputs (e.g. publications, datasets, software packages) in relation to each other. This information is stored in different systems, such as Pure, OpenAlex, Yoda, the Research Software Directory, and our organization’s employee pages.

By combining this information in one graph, it is possible to show research in context (hence the name). Ricgraph is a graph that uses nodes and edges to represent objects and their relations. It can be used to store, manipulate and read metadata of any object that has a relation to another object.

Ricgraph can answer questions like:

- Which researcher has contributed to which publication, dataset, software package, project, etc.?
- Given e.g. a dataset, software package, or project, who has contributed to it?
- What identifiers does a researcher have (e.g. ORCID, ISNI, organization employee ID, email address)?
- What skills does a researcher have?
- Show a network of researchers who have worked together?
- Which organizations have worked together?-  

With Ricgraph, you can get metadata from objects from any source system you’d like. You run the harvest script for that system, and data will be imported in Ricgraph and will be combined automatically with data which is already there. Ricgraph provides harvest scripts for the systems mentioned above. Scripts for other sources can be written easily.

Ricgraph is open source software and can be found on GitHub (https://github.com/UtrechtUniversity/ricgraph).

**Does your project fit into a category or do you want to suggest a new one?**
I think a new category may be necessary, e.g. "General software" or "Graph software". Please feel free to add this software to any category you see fit.

**Comment by J535D165** [comment]
Nice! We would welcome a PR!

**Comment by RikDTJanssen** [comment]
Dank! Natuurlijk! Maarruh, wat is een PR? Persoonlijk Record? Perfect Ricgraph? :-)

Met vriendelijke groeten,


Rik Janssen

Dr. Rik D.T. Janssen | Businessanalist | Universiteit Utrecht, Information and Technology Services | Bestuursgebouw, Heidelberglaan 8, 3584 CS Utrecht | ***@***.******@***.***> | 06 41084565 | ' www.uu.nl/ict<http://www.uu.nl/ict> | Aanwezig ma – do
________________________________

**Comment by J535D165** [comment]
Merged in #13
