### ISSUE TITLE
Add new repositories to the list

### ISSUE THREAD

**Issue by nielsjdewinter** [UtrechtUniversity/awesome-utrecht-university#4]
Dear awesome-utrecht-university,

I just learned about this repo and was wondering if you could add my projects to your list:
On my Github page (https://github.com/nielsjdewinter) I have three repo’s for the research code category:

nielsjdewinter/seasonalclumped (accompanying paper: https://cp.copernicus.org/articles/17/1315/2021/cp-17-1315-2021.html )
nielsjdewinter/DA_model (accompanying paper: https://doi.org/10.1016/j.palaeo.2019.109260)
nielsjdewinter/Aragonite_clumped (accompanying paper to be submitted)

I also developed one R package which seems to fit more within the “Research software” category:

nielsjdewinter/ShellChron (accompanying paper: https://gmd.copernicus.org/preprints/gmd-2020-401/)

Could you let me know if it is possible to add these repositories to the lists?

Thanks!
Niels de Winter
Dept. Earth Sciences

**Comment by kequach** [comment]
Dear Niels, 

thanks for your message! I had a look at your repositories and would advise the following:

- For seasonal clumped, Aragonite clumped, and ShellChron there is a nice **readme**, which is one of the [contribution requirements](https://github.com/UtrechtUniversity/awesome-utrecht-university/blob/main/CONTRIBUTING.md), well done! If you would like to add the DA_model as well, it would be good to have a nice readme here as well.
- Only Aragonite clumped has a **license**, which is another requirement. If you are unsure which one to use, you can take a look at [this website](https://choosealicense.com/) for some information about this topic.
- Lastly, while not necessary, it would be good to have [citation information](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) where it is applicable as well. Seeing how you have an accompanying paper for all repositories, I'd advise to add this to each repository as well.

Of course, we would be more than happy to help with these topics and again thank you for your interest!

On behalf of the FAIR Data and Software / Open Science Programme,
Keven Quach

**Comment by nielsjdewinter** [comment]
Dear Keven,

Thank you for your feedback.
I have now added licences and citation files wherever these were missing.
All datasets except for "DA_model" should now be ready to be added to "awesome-utrecht-university".
Over the coming weeks, I will work on the README file for the "DA_model" and let you know when that is ready so it can be added as well.

Thanks again for the support and have a nice weekend!
Niels

**Comment by kequach** [comment]
One more thing I forgot: Could you add a description to your repositories? The description text of each repository is used in this list as well. That's an oversight on my end, sorry for that.
If you would like, you can also submit a pull request with your repositories. The reason for doing this instead of having us add your repository is that you will have contributed to this list directly and you will be marked as a contributor. This will also increase visibility of your research!

**Comment by J535D165** [comment]
Nice contributions @nielsjdewinter :) I like the extensive READMEs and plots. 

If you are interested in doing a PR, please let us know. Otherwise, @kequach will add the projects for you.

**Comment by nielsjdewinter** [comment]
Thanks for your support @kequach, I just created a pull request adding names and descriptions of my repos to the list.
Note that I am not a very experienced GitHub user so I hope I did this the right way.
I did my best to follow the guidelines for the list and your suggestions, but please correct me if anything is out of order.
The only think I still need to do (I think) is add a proper README to the "DA_model" repo, I will do so as soon as possible.

**Comment by nielsjdewinter** [comment]
@J535D165 Thanks for the nice compliment! :)
I would definitely be interested in doing some PR if you think my contributions would be interesting enough.
Actually, the paper for which I wrote the ShellChron model is being typeset at the moment and will be out soon.
Perhaps its release would be a good opportunity to do some PR on this repo.
The others are already somewhat older (publications from the previous years), but if you think they are an interesting subject I would be happy to work on a description for a broader audience.

**Comment by kequach** [comment]
@nielsjdewinter I checked your pull request. The commit looks good but you need to create the pull request in **this** repository, not in the fork you created. So this needs to be done here: https://github.com/UtrechtUniversity/awesome-utrecht-university/pulls
You can find information on how to create a pull request from a fork. A fork is a copy of a repository. You can see this from the URL: https://github.com/**nielsjdewinter**/awesome-utrecht-university
If you need further help, I'd be happy to assist. Except for this, everything looks good.

**Comment by nielsjdewinter** [comment]
@kequach Sorry my bad, still didn't fully understand how it worked I guess. I now created a pull request for merging my fork with the main. Hope that will solve the issue and apply my changes to the main branch if you accept it. Please let me know if there is anything else I need to do.

**Comment by kequach** [comment]
@nielsjdewinter no worries, what we hope to achieve with this procedure is also helping you getting more familiar with these processes. Thanks again for your contributions!
